### ISSUE TITLE
Work with the connection manager

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-circuit#65]
We should integrate with the connection manager to deprioritize relay-hop connections when under heavy load.

**Comment by Stebalien** [comment]
See: https://github.com/ipfs/go-ipfs/issues/6166#issuecomment-480031995.

**Comment by vyzo** [comment]
We also need a mechanism to tag connections used as relay reservations, so that we don't drop them off the relay unnecessarily.
I think we need a `RESERVE` message, which should tag the connection in the cm.

**Comment by vyzo** [comment]
So given our observations regarding relay traffic and the discussion in #67 I think we want to do the opposite when operating as a relay. We should tag connections according to their hop count, so that when the connection manager decides to prune, we prune the idle connections first.
We might also want to have an option to explicitly enable that, as it could wreak havoc with the tagging from other subsystems.
